# Fly.io configuration for advantage-mcp-server
app = "advantage-mcp-server"
primary_region = "ewr"

[build]

[env]
  PORT = "3000"
  PYTHONUNBUFFERED = "1"
  PYTHONDONTWRITEBYTECODE = "1"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[mounts]]
  source = "knowledge_base_data"
  destination = "/data"

# Resource scaling
[deploy]
  release_command = "python -c 'print(\"Starting advantage-mcp-server\")'"

# Additional environment-specific configuration
[experimental]
  auto_rollback = true